#!/usr/bin/env bash
#
# firm-retro.sh — Consolidated retro from the last 24 h of Hermes sessions.
#
# Walks ~/.hermes/sessions/ for session_*.json modified in the last 24 h,
# collects summaries from existing marker files (or regenerates via lessons-learned
# logic), pipes them into a consolidated retro prompt, and writes the result to
# /home/ubuntubox/.hermes/memories/firm-retro-YYYYMMDD.md.
#
# SAFE: never touches state.db, MEMORY.md, or ~/.hermes/skills/.
#

set -euo pipefail

# ── deps ──────────────────────────────────────────────────────────────────────
for cmd in hermes jq date; do
  command -v "$cmd" &>/dev/null || { echo "ERROR: '$cmd' not found in PATH" >&2; exit 1; }
done

# ── paths ─────────────────────────────────────────────────────────────────────
SESSIONS_DIR="${HOME}/.hermes/sessions"
OUTPUT_DIR="/home/ubuntubox/.hermes/memories"
OUTPUT_FILE="${OUTPUT_DIR}/firm-retro-$(date +%Y%m%d).md"

# ── find sessions modified in last 24 h ───────────────────────────────────────
cutoff=$(date -d '24 hours ago' +%s 2>/dev/null || date -v-1d +%s)

mapfile -t recent_sessions < <(
  find "$SESSIONS_DIR" -maxdepth 1 \
    -name 'session_*.json' \
    -type f \
    -newermt "@${cutoff}" \
    -printf '%f\n' 2>/dev/null \
  | sort
)

if [[ ${#recent_sessions[@]} -eq 0 ]]; then
  echo "No sessions modified in the last 24 h — nothing to retro."
  exit 0
fi

echo "Found ${#recent_sessions[@]} recent session(s): ${recent_sessions[*]}"

# ── collect summaries ──────────────────────────────────────────────────────────
collected=""
for session_file in "${recent_sessions[@]}"; do
  session_path="${SESSIONS_DIR}/${session_file}"
  session_basename="${session_file%.json}"
  marker="${SESSIONS_DIR}/.lessons-done-${session_basename}"

  if [[ -f "$marker" ]]; then
    # find the corresponding lesson file written by lessons-learned.sh
    # format: lesson_<timestamp>.md
    lesson_file=$(ls "${SESSIONS_DIR}/../.claude/projects/-home-ubuntubox/memory/"/lesson_*.md 2>/dev/null \
      | grep -E "lesson_[0-9]{8}_[0-9]{4}" \
      | sort -r \
      | head -1)

    if [[ -n "$lesson_file" && -f "$lesson_file" ]]; then
      summary=$(cat "$lesson_file")
    else
      summary="[marker found but lesson file not on disk — session: ${session_basename}]"
    fi
  else
    # regenerate inline via hermes chat (same prompt as lessons-learned.sh)
    transcript=$(jq -r '
      .messages[] |
      select(.role == "assistant") |
      .content // empty
    ' "$session_path" 2>/dev/null | tail -c 8000)

    if [[ -z "$transcript" || "$transcript" == "null" ]]; then
      echo "WARN: no assistant content in $session_file — skipping" >&2
      continue
    fi

    PROMPT="You are a concise retro analyst. Read the following Hermes agent session
transcript and produce a structured summary in three sections (under 400 words total):

## What Worked
Bullet points of approaches, commands, or decisions that succeeded.

## What Surprised Us
Unexpected outcomes, surprising model behaviour, or unintended side-effects.

## What to Avoid
Actions, patterns, or habits that caused problems, confusion, or regressions.

Be specific and actionable. Do not invent information not present in the transcript.

---
TRANSCRIPT (excerpt):
${transcript:0:8000}
"
    summary=$(hermes chat --provider kimi -m kimi-k2.5 --yolo -q "$PROMPT" 2>/dev/null)

    if [[ -z "$summary" ]]; then
      echo "WARN: hermes chat returned empty for $session_file — skipping" >&2
      continue
    fi
  fi

  collected+="
========== SESSION: ${session_basename} ==========
${summary}
"
done

if [[ -z "$collected" ]]; then
  echo "No usable summaries collected — exiting."
  exit 0
fi

# ── consolidated retro ───────────────────────────────────────────────────────
RETRO_PROMPT="You are a senior trading-firm operator running a weekly retrospective.
Below are the individual session retrospectives from the last 24 hours.
Merge them into a single consolidated retro with:

1. **Overall Theme** — one sentence capturing the dominant pattern.
2. **What Went Well** — cross-session themes that worked.
3. **Surprises** — unexpected events or model behaviours.
4. **Action Items** — specific things to change, stop, or start.
5. **Risk Flags** — anything that could cause loss or operational harm if unaddressed.

Keep it under 600 words. Be blunt and actionable — this goes to a COO.

---
COLLECTED SUMMARIES:
${collected}
"

retro=$(hermes chat --provider kimi -m kimi-k2.5 --yolo -q "$RETRO_PROMPT" 2>/dev/null)

if [[ -z "$retro" ]]; then
  echo "ERROR: consolidated retro returned empty from hermes chat" >&2
  exit 1
fi

# ── write output ──────────────────────────────────────────────────────────────
mkdir -p "$OUTPUT_DIR"
cat > "$OUTPUT_FILE" <<EOF
# Firm Retro — $(date +%Y-%m-%d)

${retro}

---
Generated by firm-retro.sh | ${#recent_sessions[@]} session(s) reviewed
EOF

echo "DONE: wrote $OUTPUT_FILE"
